import request from 'supertest'
import { app } from '../src/lockpickersUnitedServer.js'
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'

// Ensure dev-like defaults so routes are under /api
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const okFetch = () => Promise.resolve({
  ok: true,
  status: 204,
  text: async () => ''
})

const rateLimitedFetch = () => Promise.resolve({
  ok: false,
  status: 429,
  text: async () => 'rate limited'
})

describe('/api/discord route', () => {
  let fetchSpy

  beforeEach(() => {
    // Reset any previous spy
    if (fetchSpy) fetchSpy.mockRestore()
  })

  afterEach(() => {
    if (fetchSpy) fetchSpy.mockRestore()
  })

  it('GET /api/discord returns info payload with requestId', async () => {
    const res = await request(app).get('/api/discord')
    expect(res.status).toBe(200)
    expect(res.body).toBeTruthy()
    expect(res.body.message).toBe('LPU Discord endpoint')
    // requestId is generated by http logger middleware
    expect(typeof res.body.requestId).toBe('string')
    expect(res.body.requestId.length).toBeGreaterThan(0)
  })

  it('POST /api/discord without message returns 400 invalid_body', async () => {
    const res = await request(app)
      .post('/api/discord')
      .send({ username: 'someone' })
      .set('Content-Type', 'application/json')

    expect(res.status).toBe(400)
    expect(res.body).toMatchObject({ error: 'invalid_body' })
  })

  it('POST /api/discord succeeds when webhook responds OK', async () => {
    fetchSpy = vi.spyOn(globalThis, 'fetch').mockImplementation(okFetch)

    const res = await request(app)
      .post('/api/discord')
      .send({ message: 'hello world', username: 'tester' })
      .set('Content-Type', 'application/json')

    expect(res.status).toBe(200)
    expect(res.body).toEqual({ ok: true })

    // Ensure our fetch was called with a plausible URL and payload
    expect(fetchSpy).toHaveBeenCalledTimes(1)
    const [calledUrl, init] = fetchSpy.mock.calls[0]
    expect(typeof calledUrl).toBe('string')
    expect(init?.method).toBe('POST')
    expect(init?.headers['Content-Type']).toContain('application/json')
  })

  it('POST /api/discord surfaces upstream failure (e.g., 429)', async () => {
    fetchSpy = vi.spyOn(globalThis, 'fetch').mockImplementation(rateLimitedFetch)

    const res = await request(app)
      .post('/api/discord')
      .send({ message: 'please slow down', username: 'tester' })
      .set('Content-Type', 'application/json')

    expect(res.status).toBe(429)
    expect(res.body.error).toBe('discord_webhook_failed')
    expect(res.body.status).toBe(429)
    expect(typeof res.body.message).toBe('string')
  })
})
